# ===================================
#  Form Behavior Config
# ===================================

name: MailLog
form: $/voilaah/maillog/models/maillog/fields.yaml
modelClass: Voilaah\MailLog\Models\MailLog

preview:
    title: View MailLog
