# ===================================
#  List Behavior Config
# ===================================

title: MailLog
list: $/voilaah/maillog/models/maillog/columns.yaml
modelClass: Voilaah\MailLog\Models\MailLog

noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

recordUrl: 'voilaah/maillog/maillogs/preview/:id'
